### ISSUE TITLE
Migrate to Quasar 1.0 across modules

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#31]
Migrate the code base to the production version.

**State of work about global migration**:
  * [x] clean the dependencies in modules/apps
  * [x] check production/build mode to ensure everything is correctly transpiled as before (eg no async/await in code to work on old devices)
    * we previously copied manually all module files in app root directory and added it as a source directory so that webpack does the job and had a DEBUG build mode disabling minification to check this
  * [x] fix travis build
    * app build fixed to trigger a deploy in dev whatever branch if !== test
  * [x] merge master that has diverged on some modules/apps with v1 branches 
  * [x] merge back v1 branches into master branch and delete v1 branches
  * update Cordova build in apps if required
    * [x] Android build works as previously
    * [x] iOS to be checked => seems that Platform.is.cordova is not working on iOS
      * kApp starts but loose the connection to the server and it is impossible to get connected
      * Akt'n'Map starts but impossible to get connected
    * [x] check if we need to update the build process, eg use quasar cli instead of cordova cli
      * as far as I can see it is not interesting and could probably interfere with our templating process 
        * the quasar cordova mode only setup a couple of cordova required files/folders like config.xml, www, etc. so it does not provide anything new
        * the quasar CLI mainly proxies the cordova CLI but also *updates* the config.xml to include [specific options ](https://quasar.dev/quasar-cli/developing-cordova-apps/configuring-cordova) like id, version, etc. and the IP @ of the dev server to connect the mobile app to it
  * [x] update end-to-end tests in apps => creating related https://github.com/kalisio/kdk/issues/38
  * [x] kNotify lint failed => creating https://github.com/kalisio/kdk/issues/39
  * fix form fields
    * [x] validation system : 
       * required fields are not checked
    * [x] as labels/hints cannot use HTML anymore in Quasar v1 we use our own elements for this now
    * [x] KAttachmentField
      * needed to move from a modal to a raw component to avoid sync issue between underlying dropzone component creation, components requiring a modal will have to manage it now
    * [x] KChipsField
    * [x] KChipsWithIconField
    * [x] KDatetimeField
    * [x] KEmailField
    * [x] KIconField
      * works but as we use FA v5 we should classify by category as we have too much icons 
    * [x] KItemField
    * [x] KNumberField
    * [x] KOptionsField
    * [x] KPasswordField
    * [x] KPhoneField
    * [x] KSelectField
    * [x] KTagField
      * styling problem to be fixed
    * [x] KTextareaField
    * [x] KTextField
    * [x] KToggleField
    * [x] KUrlField
    * [x] KLocationField
      * like uploader needed to move from a modal to a raw component to avoid sync issue between underlying map creation, components requiring a modal will have to manage it now
      * styling problem to be fixed => height and padding
  * [x] fix toasts (now QNotify) to manage background color according to error/warning/info level
    * added `toast` function in utils and `$toast` function in component to manage this, use `html` option whenever required as Quasar sanitizes now by defaults
  * [x] fix dialogs (now a plugin), need to remove the `buttons` option and enumerate ok/cancel buttons instead then linking with `onOk()/onCancel()` methods, use `html` option whenever required as Quasar sanitizes now by defaults
  * [x] fix icons for FontAwesome 5, need to add `fas` prefix whenever required
    * fixed backward compatibility of already stored icon names by forcing `fas` prefix in required components (eg event icons) using an util function `getIconName(object)`

**State of work about kApp migration, what does not seem to work properly yet**:
* [x] logout action redirect to the login page without showing the logout page
* [x] document list view style
* [x] errors displayed twice in registration, eg register with an invalid password raises 2 toasts
* [x] A scollbar is always displayed 
* [x] Add regression tests using TestCafe

**State of work about Kano migration, what does not seem to work properly yet in addition to kApp**:
* [x] added icon to manage visibility on layers/models as `q-item` does not seem to be clickable anymore
  * fixed by using `clickable v-ripple` attributes on `q-item` and `mouseover` event to detect whenever the "more menu" has to be activated
* [x] icons in layer overflow menus => could be helpful to do a KOverflowMenu to avoid duplicating code
* [x] layer action handlers
* [x] timeseries widget does not display anything on first probing, if performed again shows something but not at the right size, maximizing does not work either
* [x] geocoding form does not show up, error in console: 
  * note that it works on the deployed version 
* [x] CI build is not working

**State of work about Akt'n'Map migration, what does not seem to work properly yet in addition to kApp/Kano**:
* [x] tabs in activities do not show up (eg groups, event templates, etc.), only the first one can be active
* [x] billing plan style
* [x] event creation
  * probably linked to underlying fields not working (no helpers, item fields cannot be edited, etc.)
* [x] event template creation (with and without workflow)
  * probably linked to underlying fields not working (no helpers, icon fields cannot be edited, etc.)
* [x] events activity
  * media upload/browsing
* [x] event activity => media browser does not open in fullscreen mode
  * _cnouguier_: seems to work (non reproductable)
* [x] participant panel in event activity
* [x] layers panel in catalog activity does not open
* [x] card rendering (eg members)
* [x] overflow menu in cards
* [x] overflow menu in app bar
* [x] settings cannot be open
* [x] help carousel
* [x] layer icons in panel (probably related to the use of Font Awesome 5)
* [x] terms page
* [x] hyperlinks work on screens but without hyperlink style
* [x] when closing an editor modal on a dedicated route the router does not go back in history
* [x] because icon names have changed we might need to migrate the database if cannot force `fas` prefix in all required components => creating https://github.com/kalisio/aktnmap/issues/86
* [x] KAlertSignup is displayed below the AppBar
* [x] KAccountDevices cannot be mounted
* [x] The register operation fails => not related to the migration

**Comment by claustres** [comment]
State of work about Kano migration, what does not seem to work properly yet:
* icons in layer overflow menus
* attachment field in create layer form
* no helper on toggle field in settings form
* html links not correctly displayed in some helpers in settings form
* timeseries widget does not display anything on first probing, if performed again shows something but not at the right size, maximizing does not work either

**Comment by cnouguier** [comment]
Still some work to carry on : 

- Cleaning the dependencies
- Testing Cordova

**Comment by leob** [comment]
Update on the issues (I'm unable to edit the original comment) - I think a number of issues mentioned there have been fixed/addressed now:

- fix fields validation  =>  don't know exactly what the issues are, but in kApp (document editor) the field validations work correctly now (the problem was related to QSelect/KSelectField, I've fixed that)
- fix toasts  =>  yes we now have a $toast function/plugin
- kApp: "logout although disconnecting route /logout does seem to work"  =>  I think logout works fine now in kApp
- kApp: "document list view style"  =>  I've fixed this yesterday
- Kano: "no helper on toggle field in settings form"  =>  I fixed the KToggleField yesterday (specifically the hint/helper) - see KRegister form
- Kano: "html links not correctly displayed in some helpers in settings form"  =>  also made a fix for that in KToggleField - see KRegister form
- Aktnmap: "most forms have no helpers, fields cannot be edited"  =>  some form components have already been fixed in KCore, e.g. KTextField, KSelect, KToggleField and so on - I will fix a bunch more today (the problem is that QField and the other field components now work differently especially with regards to hint/label etc)
- Aktnmap: "hyperlinks work on screens but without hyperlink style" - this is already fixed in kApp and in Kano, I've added some styles in app.styl (and in quasar.variables.styl) to fix this

So I think quite a lot of these issues have been fixed already, in some cases the fix would need to be 'ported' from kApp to Kano or Aktnmap.

**Comment by leob** [comment]
Update on the issues (I'm unable to edit the original comment):

NOT fixed yet:

- after the user signs up (KRegister), the app does not redirect to the home page - it remains on the register page, which to the user appears like "nothing happens"

I think a number of issues mentioned there have been fixed/addressed now:

- fix fields validation => don't know exactly what the issues are, but in kApp (document editor) the field validations work correctly now (the problem was related to QSelect/KSelectField, I've fixed that)
- fix toasts => yes we now have a $toast function/plugin
kApp: "logout although disconnecting route /logout does seem to work" => I think logout works fine now in kApp
- kApp: "document list view style" => I've fixed this yesterday
- Kano: "no helper on toggle field in settings form" => I fixed the KToggleField yesterday (specifically the hint/helper) - see KRegister form
- Kano: "html links not correctly displayed in some helpers in settings form" => also made a fix for that in KToggleField - see KRegister form
- Aktnmap: "most forms have no helpers, fields cannot be edited" => some form components have already been fixed in KCore, e.g. KTextField, KSelect, KToggleField and so on - I will fix a bunch more today (the problem is that QField and the other field components now work differently especially with regards to hint/label etc)
- Aktnmap: "hyperlinks work on screens but without hyperlink style" - this is already fixed in kApp and in Kano, I've added some styles in app.styl (and in quasar.variables.styl) to fix this

So I think quite a lot of these issues have been fixed already, in some cases the fix would need to be 'ported' from kApp to Kano or Aktnmap.

**Comment by leob** [comment]
Update on the issues (I'm unable to edit the original comment):

NOT fixed yet:

- after the user signs up (KRegister), the app does not redirect to the home page - it remains on the register page, which to the user appears like "nothing happens"
I think a number of issues mentioned there have been fixed/addressed now:

- fix fields validation => don't know exactly what the issues are, but in kApp (document editor) the field validations work correctly now (the problem was related to QSelect/KSelectField, I've fixed that)
- fix toasts => yes we now have a $toast function/plugin
kApp: "logout although disconnecting route /logout does seem to work" => I think logout works fine now in kApp
- kApp: "document list view style" => I've fixed this yesterday
Kano: "no helper on toggle field in settings form" => I fixed the KToggleField yesterday (specifically the hint/helper) - see KRegister form
- Kano: "html links not correctly displayed in some helpers in settings form" => also made a fix for that in KToggleField - see KRegister form
- Aktnmap: "most forms have no helpers, fields cannot be edited" => some form components have already been fixed in KCore, e.g. KTextField, KSelect, KToggleField and so on - I will fix a bunch more today (the problem is that QField and the other field components now work differently especially with regards to hint/label etc)
- Aktnmap: "hyperlinks work on screens but without hyperlink style" - this is already fixed in kApp and in Kano, I've added some styles in app.styl (and in quasar.variables.styl) to fix this
So I think quite a lot of these issues have been fixed already, in some cases the fix would need to be 'ported' from kApp to Kano or Aktnmap.

**Comment by cnouguier** [comment]
KSignupAlerr is still using some old code (QCollapsible) and it is displayed under the AppBar in Akt'n'Map => consider using a generic QBanner

**Comment by cnouguier** [comment]
Quasar is providing a global event bus: https://quasar.dev/options/global-event-bus#Introduction => it is worth using it

**Comment by leob** [comment]
> Quasar is providing a global event bus: https://quasar.dev/options/global-event-bus#Introduction => it is worth using it

If you read carefully, it says that Vue has an event bus, not Quasar. The old version of Quasar had an event bus (so we used that), but with version 1 they've dropped it. The way we do it now (through the 'Events' class or this.$events) uses the Vue event bus.

**Comment by leob** [comment]
I've looked at the Build process, so the output of a production build via the command:
```
yarn build
```
(or `npm run build`).

I've tested this with the "old" kApp version (kApp and kCore from before the Quasar migration), and the "new" kApp version (post migration). My conclusions are:

1- The copy step (copying kCore etcetera to the app directory), which the old build scripts did, does not seem to be necessary anymore. I've verified this as follows:

First I made a build with new app by excuting `yarn build` in the root of the kApp project.

Then I went to the "api" directory under kApp, and did a `yarn build` and `yarn prod` there. I could then view and test the app via localhost:8081.

Conclusion was that the app (built with`yarn build` and *without* the "copy files step") worked correctly (tested login, logout, demo page, document editor etc)

2- I also did a `yarn build` with the *old* version of the app (maste branch, before the Quasar migration). I observed that the 'new' build (size of the `dist/spa` directory) is actually smaller than the 'old' build (size of the `dist`):

- size of the 'old' build (`dist`): 5.2 MB 

- size of the 'new' build (`dist/spa`): 4.2 MB 

3- The 'old' build scripts had a "debug" mode where you could do a 'production' build but without the minification step (so that the output is "readable" Javascript which can e.g. be used for debugging).

I've modified quasar.conf.js to support this feature. So if you perform a build like this:
```
   DEBUG = 1 yarn build
```
then a "debug build" will be produced in `dist/spa`. Using this "debug" build, I was able to verify that the build output consists of Javascript that is correctly transpiled (for instance, does not contain "async" or "await").

Note: as described under 2, the bundle size is already smaller in the new build than it was in the old build. If we want to attempt to further optimize this (or if we want to analyze why the bundle size is smaller), then we might take a look at `webpack-bundle-analyzer`:

https://github.com/webpack-contrib/webpack-bundle-analyzer

**Comment by cnouguier** [comment]
Concerning the registration operation that fails in Akt'n'Map, here is the log on: 
```
error: error: api/organisations - Method: create: Cannot read property 'call' of undefined TypeError: Cannot read property 'call' of undefined
aktnmap_app.1.ln04y27stknv@dev-worker-1    |     at Object.createOrganisationServices (/opt/aktnmap/api/dist/hooks/hooks.organisations.js:16:32)
aktnmap_app.1.ln04y27stknv@dev-worker-1    |     at promise.then.hookObject (/opt/aktnmap/modules/kCore/node_modules/@feathersjs/commons/lib/hooks.js:142:73
````
